### ISSUE TITLE
Clickable link for resetting password

### ISSUE THREAD

**Issue by keiko713** [heroku/identity#132]
It would be nice if "https://id.heroku.com/account/password/reset" part is clickable:

![](http://cl.ly/image/0D3z1J303h3c/Screen%20Shot%202015-01-10%20at%208.08.00%20AM.png)

Seems like it's just showing an error message from API so not sure if you'd like to change it though.

**Comment by brandur** [comment]
@keiko713 Thanks!

Fixed in #134.
