### ISSUE TITLE
Mobile Deny/Allow Access Buttons

### ISSUE THREAD

**Issue by mattgraham** [heroku/identity#135]
![screenshot 2015-01-16 12 22 12](https://cloud.githubusercontent.com/assets/51578/5784385/9f268592-9d99-11e4-8aa1-f6e3d8153f69.png)

In following a link emailed I noticed that the Deny/Allow Buttons are not viewable on the iPhone(5S) and I would imaging other mobile devices. Being new to Heroku you can let me know how you would prefer I handle issues like this; ie pull request or this issue and a :wave:  

Can either 

- Add @mobile query and make the buttons 100% width on mobile devices...
```
@media only screen 
and (min-device-width : 375px) and (max-device-width : 667px) { 
  .split .btn {
    width: 100%;
    margin-right: 0%;
    margin-bottom: 10px;
  }
}
```
- Kill the word "Access" (Allow/Deny only) 

or

- Get fancy with responsive text (which seems like a bit much for this one off).

**Comment by brandur** [comment]
@mattgraham Right on Matt! Thank-you.

> Kill the word "Access" (Allow/Deny only)

I'm +1 this solution; I like the simplicity. We've already got the word "access" well-explained in the main body, and I'm not sure that having it in the buttons as well really helps to clarify anything.

@ntassone @raul Any thoughts/opinions on this one?

**Comment by mattgraham** [comment]
I'd be overjoyed to have my first PR happen week one if you want me to whip it up.


:boom:


Matt Graham, UX Design & Strategy
kickthebox@gmail.com

**Comment by brandur** [comment]
Matt: yes, go for it! You can even deploy the fix if you like.
