### ISSUE TITLE
Maintenance page has white on white text

### ISSUE THREAD

**Issue by dmcinnes** [heroku/identity#225]
![screen shot 2016-05-17 at 10 26 13 am](https://cloud.githubusercontent.com/assets/16557/15332282/d3943086-1c19-11e6-83af-af7d25553591.png)

**Comment by dmcinnes** [comment]
Should also link to our support page.

**Comment by raul** [comment]
Status page? (I'd +1 that).

**Comment by dmcinnes** [comment]
Ah oops yes I mean status 😄  https://status.heroku.com/

**Comment by dmcinnes** [comment]
Moved the status suggestion to https://github.com/heroku/identity/issues/229
