### ISSUE TITLE
id.heroku.com/signup/ok route still being hit

### ISSUE THREAD

**Issue by dominic** [heroku/identity#46]
> From what I can tell, signup success now posts to id.heroku.com/account, yet I still see a trickle of traffic to id.heroku.com/signup/ok, which as far as I can tell, shouldn't be happening.

> http://cl.ly/image/361x37103g14

> Any idea what's going on? Is it api.heroku.com/signup/ok redirecting? Is it just us testing that URL? 21 times in the last month...

**Comment by dmcinnes** [comment]
No longer appears to be an issue. Closing...
