### ISSUE TITLE
Exception when a suspended account tries to log in

### ISSUE THREAD

**Issue by raulb** [heroku/identity#53]
When a suspended account tries to log in, we don't provide any valuable information. Instead, it throws an exception with this error message:

![image](https://f.cloud.github.com/assets/306015/971454/d2c03326-05e7-11e3-9b5a-e0c8ab3972d0.png)

If an account is suspended due to overdue balances (right now we only can check that on the recently [added notes](https://github.com/heroku/heroku-sudo/commit/7be97b15fada53beac8e9cd47319f03f6bbd5a62)), we shouldn't log out those accounts and instead, send them to https://vault.heroku.com/pay-balance.

On a side note, we might want to think about a better way to indicate the reason of suspension (whether is a suspended account because they abused the api or because they have unpaid balance). Having notes explaining the reason is great but I think we should provide another way to make easier an automated process for [unsuspending accounts](https://github.com/heroku/vault-team/blob/master/specifications/delinquent-accounts.md).

More information, see https://herokuapp10678129herokucom.airbrake.io/groups/55786861.

```ruby
Excon::Errors::UnprocessableEntity: Expected(201) <=> Actual(422 Unprocessable Entity) request => {:chunk_size=>1048576, :connect_timeout=>60, :headers=>{"Accept"=>"application/vnd.heroku+json; version=2", "Content-Type"=>"application/x-www-form-urlencoded", "Request-ID"=>"7e01844b-1a30-481d-8678-5111490a0e00", "X-Forwarded-For"=>"152.179.69.246", "Authorization"=>"Basic bWF4K3JlYWxseStzdXNwZW5kZWRAaGVyb2t1LmNvbTplbnRlcm5vd29ybGV0bWVpbg==", "Host"=>"api.heroku.com:443", "Content-Length"=>134}, :instrumentor_name=>"excon", :mock=>false, :nonblock=>true, :read_timeout=>60, :retry_limit=>4, :ssl_ca_file=>"/app/vendor/bundle/ruby/2.0.0/gems/excon-0.16.10/data/cacert.pem", :ssl_verify_peer=>true, :write_timeout=>60, :host=>"api.heroku.com", :host_port=>"api.heroku.com:443", :path=>"/oauth/tokens", :port=>"443", :query=>nil, :scheme=>"https", :instrumentor=>#<Identity::ExconInstrumentor:0x007fe6e59e39e0 @extra_data={:request_id=>"7e01844b-1a30-481d-8678-5111490a0e00"}>, :expects=>201, :body=>"code=c3f15bcc-45fc-4f5b-abf3-746261116314&client_secret=c7b196131dacb084fb8640b40a7e1173778476f30909401e&grant_type=authorization_code", :method=>:post} response => #<Excon::Response:0x007fe6e5a2bc40 @body="{\"id\":\"suspended\",\"error\":\"The account max+really+suspended@heroku.com was suspended. If you believe this is an error please contact support\"}", @headers={"Cache-Control"=>"no-transform", "Content-Type"=>"application/json;charset=utf-8", "Date"=>"Thu, 15 Aug 2013 19:02:02 GMT", "Request-Id"=>"c50daad5-07af-42f8-9717-ef1bf623772c", "Server"=>"nginx/1.2.8", "Status"=>"422 Unprocessable Entity", "Strict-Transport-Security"=>"max-age=31536000", "X-Content-Type-Options"=>"nosniff", "X-RateLimit-Remaining"=>"2397", "X-Runtime"=>"0.197467954", "Content-Length"=>"142", "Connection"=>"keep-alive"}, @status=422>
```

cc @heroku/the-vault @max

**Comment by dmcinnes** [comment]
This appears to still happen.
Most recent ticket: https://support.heroku.com/tickets/209858

**Comment by geemus** [comment]
Do we know if this is still a thing?

**Comment by dmcinnes** [comment]
Looks like we're OK:

![screen shot 2015-11-11 at 4 18 21 pm](https://cloud.githubusercontent.com/assets/16557/11107159/ea76e046-888f-11e5-964d-060cea478236.png)

**Comment by thanhnguyen2359** [comment]
Hi , i have the similar too . Today , i'm login to heroku and found this error 
![screen shot 2015-12-30 at 12 25 54](https://cloud.githubusercontent.com/assets/7357943/12046705/836f0b26-aef0-11e5-9354-3d09f093dc63.png)

**Comment by raulb** [comment]
@thanhnguyen2359 Have you reached out our Support Team to find out the root cause of this error?

You can contact them by opening a ticket on https://help.heroku.com/tickets/new?query=help.

**Comment by thanhnguyen2359** [comment]
Hi Raul, currently I can't login so couldn't open ticket on heroku.
But i think the reason is by this app :
https://dbs-ibanking-demo.herokuapp.com/
Today, i found google raise it is an Phishing site so i think that why
heroku suspend my account ,
I have submit the mistake to google and heroku , Google restored the link
but heroku still not restore my account :(

Sincerely,
Thanh Nguyen Kim
